#!/bin/bash 
#simple bash script that starts direwolf and sends all data to a log file with a timestamp for each entry.
direwolf -c ~.direwolf.conf -r 24000 -D 1 | ts "%b %d %y %H:%M:%S %Z" | tee -a ~/Documents/APRS.log
