#!/bin/bash
#This Script is a modification of two scripts.
# https://github.com/craigerl/aprs-send-weather/blob/main/aprs-send-weather.sh  
# https://groups.io/g/direwolf/message/7007
# Both by Craig KM6LYW
# The new script was assembled by Robert W9RWB
# The purpose is to send messages to the ISS and other APRS satellites the use ARISS via the commandline rather than using a client such as YAAC or Xastir.
# read time in minutes from command line
btime=$1
if [ "$btime" == "" ]; then
  echo "Usage:  $1 <Enter time in minutes with no units>"
  exit 1
fi
runtime="$1 minute"
endtime=$(date -ud "$runtime" +%s)

USER="enter your callsign with aprs identifier number"
DIREWOLFHOSTNAME=localhost
while [[ $(date -u +%s) -le $endtime ]]
do

echo "Sending packet to Radio TNC."
{
sleep 10    # allow kissutil time to make connection
#change line bellow with your location, antenna information, and message
printf  "$USER>CQ,ARISS,WIDE2-1:!4140.89NI08612.21W#PHG2000 Hello from Robert" 
} | kissutil -h $DIREWOLFHOSTNAME

done
